### ISSUE TITLE
Unknown character

### ISSUE THREAD

**Issue by enfarious** [erupt321/ruptchat#1]
I'm not sure if this is an issue with my end or the addon, which I think if awesome btw!
On some lines that should have a cr/lf there is instead an unknown character block.

The 2 things I've seen this on as of right now are:
1: The ancient magic of King Kupofried fills the air, its glorious Super Kupowers bringing happiness and joy to the realm![?]Visit the Explorer Moogle in Ru'Lude Gardens to find out more.

2: After Domain Invasion there is a block that has many a newline character that isn't newlining.

Thank you for creating an awesome modern chatlog for this beloved game :)

**Comment by erupt321** [comment]
Issue occurs when saving with unfiltered line breaks.  Added \r check in addition to regular line break and seems to be fixed.
