### ISSUE TITLE
Assist flags not working

### ISSUE THREAD

**Issue by alchemicdreams** [erupt321/ruptchat#7]
Just set the addon up this week and it doesn't seem to be working with messages in the assist channel. Every time one comes in I get the following error in the windower console:

**RuptChat: Lua runtime error: ruptchat/text_processing.lua:469: attempt to index global 'assist_flags' (a nil value)**

**Comment by erupt321** [comment]
Yeah I forgot the upload the updated globals.lua which has the assist_flags table.  Updated it now, so just redownload the globals file.

**Comment by alchemicdreams** [comment]
Thank you very very much.
